# Generated by Django 5.0.4 on 2024-04-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDynamicData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
